name: 'Helm Push Action'
description: 'Deploy new version of Serverless function to Yandex Cloud'
author: 'Goodsmileduck'
branding:
  color: 'blue'
  icon: 'upload-cloud'
inputs: 
  CloudId:
    description: 'Helm push to chartmuseum'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  
